from django.core.management.base import BaseCommand
from random import sample, randint, choice

from qweeco.board.models import Message

lipsum = ["lorem","ipsum","dolor","sit","amet","consectetur","adipiscing","elit","curabitur","ut","finibus","mi","a","consequat","orci","nunc","eu","efficitur","orci","Fusce","tincidunt","urna","ac","diam","placerat","id","ullamcorper","nisl","elementum","aliquam","egestas","mi","et","vestibulum","interdum","lacus","sem","porta","nibh","at","semper","leo","nisi","a","nisl","aenean","venenatis","ex","orci","ac","pulvinar","lorem","tempus","vel","vestibulum","posuere","euismod","ligula","nec","posuere","etiam","ultricies","condimentum","vestibulum","nam","eu","erat","massa","phasellus","fermentum","ante","ac","tortor","iaculis","porttitor","Fusce","bibendum","enim","tempor","tincidunt","nunc","sed","mollis","lorem","donec","vehicula","orci","libero","eget","rhoncus","diam","scelerisque","congue","proin","tempor","massa","et","iaculis","accumsan","nisl","ipsum","molestie","dolor","eget","iaculis","augue","leo","eu","tellus","nullam","lorem","felis","fringilla","sed","consectetur","id","consequat","eget","velit","nulla","id","malesuada","lacus","a","volutpat","urna","nulla","ultricies","velit","sit","amet","facilisis","interdum","enim","arcu","dictum","nisl","ac","mollis","leo","orci","vitae","nulla","Integer","ultrices","malesuada","purus","aliquam","ultricies","vel","velit","a","lobortis","curabitur","blandit","facilisis","lacus","sit","amet","mollis","lacus","sodales","quis","aenean","mollis","ut","mi","vitae","aliquet","maecenas","porta","lacus","eget","nunc","elementum","nec","vulputate","massa","imperdiet","integer","ut","ullamcorper","diam","ac","semper","neque","sed","vitae","ipsum","id","leo","consectetur","mattis","a","mollis","eros","vestibulum","eros","nunc","rutrum","eleifend","vestibulum","ac","imperdiet","ut","purus","vestibulum","sit","amet","tellus","ultricies","metus","venenatis","bibendum","vivamus","urna","ex","ornare","vel","nibh","et","feugiat","rhoncus","ex","pellentesque","at","felis","quis","diam","feugiat","ullamcorper","id","at","dui","nulla","non","nisl","non","risus","rutrum","tempor","duis","lacinia","volutpat","mauris","in","finibus","ante","interdum","eget","fusce","porta","est","quis","libero","scelerisque","et","sagittis","tortor","dapibus","duis","in","semper","metus","eu","luctus","massa","pellentesque","nec","porttitor","orci"]

class Command(BaseCommand):
    def handle(self, *args, **options):
    	for x in range(1,54):
    		Message.objects.create(email=choice(lipsum) + '@' + choice(lipsum) + '.net', text=' '.join(sample(lipsum, randint(9,19) )))
